export const THEME_COLORS = {
  WHITE: '#FFFFFF',
  GREY: '#F4F4F4',
  GREY_MEDIUM: '#E6E6E6',
  GREY_DARK: '#A0A0A0',
  BLACK: '#000',
  PLACEHOLDER: '#CFCFCF',
  PURPLE: '#770FDF',
  PURPLE_LIGHT: '#F7EFFF',
  GREEN: '#0FDF8F',
  RED: '#EE8688'
}
